name: sunafxinet

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.9,<3.10
  - ffmpeg>=4.2
  - pytorch>=2.5.1
  - torchaudio>=0.8
  - tqdm>=4.36
  - pip
  - pip:
    - auraloss=0.4.0
    - diffq>=0.2
    - dora-search
    - einops
    - hydra-colorlog>=1.1
    - hydra-core>=1.1
    - julius>=0.2.3
    - lameenc>=1.2
    - openunmix
    - musdb>=0.4.0
    - museval>=0.4.0
    - pedalboard=0.9.17
    - soundfile
    - submitit
    - torchmetrics=1.8.2
    - treetable>=0.2.3
